export default {
    'add':{ //新增
        'colors':'primary',
        'name_zh_CN':'新增',
        'name_zh_TW':'新增',
        'name_en_US':'New',
        'hotkey':'alt+n',
        'className':'ac-btns-add'
    },
    'confirm':{ //确认
        'colors':'primary',
        'name_zh_CN':'确认',
        'name_zh_TW':'確認',
        'name_en_US':'Confirm',
        'className':'ac-btns-confirm'
    },
    'detail':{ //详情
        'colors':'write',
        'name_zh_CN':'详情',
        'name_zh_TW':'詳情',
        'name_en_US':'Details',
        'className':'ac-btns-detail'
    },
    'search':{//查询
        'colors':'primary',
        'name_zh_CN':'查询',
        'name_zh_TW':'查詢',
        'name_en_US':'Search',
        'hotkey':'ctrl+enter',
        'className':'ac-btns-search'
    },
    'clear':{//清空
        'colors':'write',
        'name_zh_CN':'清空',
        'name_zh_TW':'清空',
        'name_en_US':'Clear',
        'hotkey':'ctrl+r',
        'className':'ac-btns-clear'
    },
    'empty':{//置空
        'colors':'write',
        'name_zh_CN':'清空',
        'name_zh_TW':'清空',
        'name_en_US':'Clear',
        'hotkey':'ctrl+r',
        'className':'ac-btns-empty'
    },
    'export':{//导出
        'colors':'write',
        'name_zh_CN':'导出',
        'name_zh_TW':'導出',
        'name_en_US':'Export',
        'hotkey':'',
        'className':'ac-btns-export'
    },
    'import':{//导入
        'colors':'write',
        'name_zh_CN':'导入',
        'name_zh_TW':'導入',
        'name_en_US':'Import',
        'hotkey':'',
        'className':'ac-btns-import'
    },
    'template':{//导入模板下载
        'colors':'write',
        'name_zh_CN':'导入模板下载',
        'name_zh_TW':'導入模板下載',
        'name_en_US':'Import template download',
        'hotkey':'',
        'className':'ac-btns-template'
    },
    'save':{//保存
        'colors':'primary',
        'name_zh_CN':'保存',
        'name_zh_TW':'保存',
        'name_en_US':'Save',
        'hotkey':'',
        'className':'ac-btns-save'
    },
    'cancel':{//取消
        'colors':'write',
        'name_zh_CN':'取消',
        'name_zh_TW':'取消',
        'name_en_US':'Cancel',
        'hotkey':'',
        'className':'ac-btns-cancel'
    },
    'update':{//修改
        'colors':'write',
        'name_zh_CN':'修改',
        'name_zh_TW':'修改',
        'name_en_US':'Modify',
        'hotkey':'',
        'className':'ac-btns-update'
    },
    'delete':{//删除
        'colors':'write',
        'name_zh_CN':'删除',
        'name_zh_TW':'刪除',
        'name_en_US':'Delete',
        'hotkey':'',
        'className':'ac-btns-delete'
    },
    'pbmsubmit':{//提交
        'colors':'write',
        'name_zh_CN':'提交',
        'name_zh_TW':'提交',
        'name_en_US':'Submit',
        'hotkey':'',
        'className':'ac-btns-pbmsubmit'
    },
    'pbmcancle':{//撤回
        'colors':'write',
        'name_zh_CN':'撤回',
        'name_zh_TW':'撤回',
        'name_en_US':'Recall',
        'hotkey':'',
        'className':'ac-btns-pbmcancle'
    },
    'pbmapprove':{//审批
        'colors':'write',
        'name_zh_CN':'审批',
        'name_zh_TW':'審批',
        'name_en_US':'Approval',
        'hotkey':'',
        'className':'ac-btns-pbmapprove'
    },
    'appoint': { //指派
        'colors': 'write',
        'name_zh_CN': '指派',
        'name_zh_TW': '指派',
        'name_en_US': 'Appoint',
        'hotkey': '',
        'className': 'ac-btns-appoint'
    },
    'printpreview':{//打印预览
        'colors':'write',
        'name_zh_CN':'打印预览',
        'name_zh_TW':'打印預覽',
        'name_en_US':'Print Preview',
        'className':'ac-btns-printpreview'
    },
    'printdesign':{//打印设计
        'colors':'write',
        'name_zh_CN':'打印设计',
        'name_zh_TW':'打印設計',
        'name_en_US':'Print Design',
        'className':'ac-btns-printdesign'
    },
    'upload':{//上传
        'colors':'primary',
        'name_zh_CN':'上传',
        'name_zh_TW':'上傳',
        'name_en_US':'Upload',
        'className':'ac-btns-upload'
    },
    'reupload':{//重新上传
        'colors':'primary',
        'name_zh_CN':'重新上传',
        'name_zh_TW':'重新上傳',
        'name_en_US':'Re-upload',
        'className':'ac-btns-reupload'
    },
    'download':{//下载
        'colors':'write',
        'name_zh_CN':'下载',
        'name_zh_TW':'下載',
        'name_en_US':'Download',
        'className':'ac-btns-download'
    },
    'addRow':{//增行
        'colors':'write',
        'name_zh_CN':'增行',
        'name_zh_TW':'增行',
        'name_en_US':'New',
        'className':'ac-btns-addRow'
    },
    'delRow':{//删行
        'colors':'write',
        'name_zh_CN':'删行',
        'name_zh_TW':'刪行',
        'name_en_US':'Delete',
        'className':'ac-btns-delRow'
    },
    'copyRow':{//复制行
        'colors':'write',
        'name_zh_CN':'复制行',
        'name_zh_TW':'複製行',
        'name_en_US':'Duplicate rows',
        'className':'ac-btns-copyRow'
    },
    'max':{//最大化
        'colors':'write',
        'name_zh_CN':'最大化',
        'name_zh_TW':'最大化',
        'name_en_US':'Maximize',
        'className':'ac-btns-max'
    },
    'min':{//最小化
        'colors':'write',
        'name_zh_CN':'min',
        'name_zh_TW':'最小化',
        'name_en_US':'Minimize',
        'className':'ac-btns-min'
    },
    'copyToEnd':{//粘贴至末行
        'colors':'write',
        'name_zh_CN':'粘贴至末行',
        'name_zh_TW':'粘貼至末行',
        'name_en_US':'Paste to end line',
        'className':'ac-btns-copyToEnd'
    },
    'organizationChat':{//机构图
        'colors':'write',
        'name_zh_CN':'机构图',
        'name_zh_TW':'機構圖',
        'name_en_US':'Organization Chat',
        'className':'ac-btns-organizationChat'
    },
    'enable':{//启用
        'colors':'write',
        'name_zh_CN':'启用',
        'name_zh_TW':'啟用',
        'name_en_US':'Enable',
        'className':'ac-btns-enable'
    },
    'disabled':{//停用
        'colors':'write',
        'name_zh_CN':'停用',
        'name_zh_TW':'停用',
        'name_en_US':'Disabled',
        'className':'ac-btns-disabled'
    },
    'next':{//下一条
        'colors':'write',
        'name_zh_CN':'下一条',
        'name_zh_TW':'下一條',
        'name_en_US':'Next',
        'className':'ac-btns-next'
    },
    'previous':{//上一条
        'colors':'write',
        'name_zh_CN':'上一条',
        'name_zh_TW':'上一條',
        'name_en_US':'Previous',
        'className':'ac-btns-previous'
    },
    'first':{//第一条
        'colors':'write',
        'name_zh_CN':'第一条',
        'name_zh_TW':'第一條',
        'name_en_US':'First',
        'className':'ac-btns-first'
    },
    'last':{//最后一条
        'colors':'write',
        'name_zh_CN':'最后一条',
        'name_zh_TW':'最後一條',
        'name_en_US':'Last',
        'className':'ac-btns-last'
    },
}
